In [1]:
import pandas as pd
import numpy as np

# Dictionaries

In [2]:
# https://teamcolorcodes.com/ncaa-color-codes/sec-team-color-codes/

sec_color_dict = {
    'ALA': '#9e1b32', 'MISS': '#14213D', 'MIZ': '#F1B82D', 'SC': '#000000',
    'VAN': '#866d4b', 'TA&M': '#500000', 'LSU': '#461D7C', 'AUB': '#0C2340', 
    'UGA': '#BA0C2F', 'FLA': '#0021A5', 'MSST': '#660000', 'TENN': '#FF8200', 
    'ARK': '#9D2235', 'UK': '#0033a0'
}

In [3]:
sec_name_dict = {
    'ALA': 'Alabama', 'MISS': 'Ole Miss', 'MIZ': 'Missouri', 'SC': 'South Carolina',
    'VAN': 'Vanderbilt', 'TA&M': 'Texas A&M', 'LSU': 'LSU', 'AUB': 'Auburn', 
    'UGA': 'Georgia', 'FLA': 'Florida', 'MSST': 'Miss State', 'TENN': 'Tennessee', 
    'ARK': 'Arkansas', 'UK': 'Kentucky'    
}

In [4]:
conf_dict = {
    'SEC': ['ALA', 'MISS', 'MIZ', 'SC', 'VAN', 'TA&M', 'LSU', 'AUB', 'UGA', 'FLA', 'MSST', 'TENN', 'ARK', 'UK'],
    'Big10': ['OSU', 'PUR', 'NW', 'MSU'], 
    'ACC': ['NCST', 'CLEM'], 
    'Pac12': ['WSU'], 
    'Big12': ['OKLA', 'OKST', 'TEX']
}

inv_conf_dict = {v: k for k, values in conf_dict.items() for v in values}

# Dataframe

In [24]:
df = pd.read_csv('CFB_QBs_2018.csv')

df['Conference'] = df['Team'].map(inv_conf_dict)
df['TeamName'] = df['Team'].map(sec_name_dict)
df['TeamColor'] = df['Team'].map(sec_color_dict)
df['TennColor'] = '#74ABD6'
df['TennColor'] = np.where(df['Team'] == 'TENN', '#f77f00', df['TennColor'])


df['Player'] = df['Player'].str.split(',', expand=True)[0]

df['YPC'] = np.round(df['Yards'] / df['Completions'],1)
df['AttemptsPerINT'] = np.round(df['Attempts'] / df['INTs'],1)
df['INTModYards'] = df['Yards'] - (df['INTs'] * 50)
df['INTModYardsPerAtt'] = np.round(df['INTModYards'] / df['Attempts'],2)
df['AttemptsPerSack'] = np.round((df['Attempts'] + df['SacksTaken']) / df['SacksTaken'], 2)

df = df.drop(['Rank'], axis=1)


df = df[['Player', 'Team', 'TeamName', 'TeamColor', 'TennColor', 'Conference', 'Completions', 'Attempts',
       'CompletionPct', 'Yards', 'YPA', 'YPC', 'Long', 'TDs', 'INTs', 'SacksTaken',
       'QBRating', 'AttemptsPerINT', 'INTModYards', 'INTModYardsPerAtt', 'AttemptsPerSack']]

# df.columns = ['Player', 'Team', 'Conference', 'Completions', 'Attempts',
#        'Completion %', 'Yards', 'YPA', 'YPC', 'Long', 'TDs', 'INTs', 'Attempts per INT','Sacks Taken',
#        'QB Rating']

In [25]:
df.columns

Index(['Player', 'Team', 'TeamName', 'TeamColor', 'TennColor', 'Conference',
       'Completions', 'Attempts', 'CompletionPct', 'Yards', 'YPA', 'YPC',
       'Long', 'TDs', 'INTs', 'SacksTaken', 'QBRating', 'AttemptsPerINT',
       'INTModYards', 'INTModYardsPerAtt', 'AttemptsPerSack'],
      dtype='object')

In [26]:
df.head()

,Player,Team,TeamName,TeamColor,TennColor,Conference,Completions,Attempts,CompletionPct,Yards,...,YPC,Long,TDs,INTs,SacksTaken,QBRating,AttemptsPerINT,INTModYards,INTModYardsPerAtt,AttemptsPerSack
0,Dwayne Haskins,OSU,NaN,NaN,#74ABD6,Big10,373,533,70.0,4831,...,13.0,78,50,8,20,174.1,66.6,4431,8.31,27.65
1,Gardner Minshew,WSU,NaN,NaN,#74ABD6,Pac12,468,662,70.7,4779,...,10.2,89,38,9,13,147.6,73.6,4329,6.54,51.92
2,Kyler Murray,OKLA,NaN,NaN,#74ABD6,Big12,260,377,69.0,4361,...,16.8,86,42,7,18,199.2,53.9,4011,10.64,21.94
3,Taylor Cornelius,OKST,NaN,NaN,#74ABD6,Big12,288,485,59.4,3978,...,13.8,64,32,13,32,144.7,37.3,3328,6.86,16.16
4,Tua Tagovailoa,ALA,Alabama,#9e1b32,#74ABD6,SEC,245,355,69.0,3966,...,16.2,81,43,6,13,199.5,59.2,3666,10.33,28.31

In [27]:
df.columns

Index(['Player', 'Team', 'TeamName', 'TeamColor', 'TennColor', 'Conference',
       'Completions', 'Attempts', 'CompletionPct', 'Yards', 'YPA', 'YPC',
       'Long', 'TDs', 'INTs', 'SacksTaken', 'QBRating', 'AttemptsPerINT',
       'INTModYards', 'INTModYardsPerAtt', 'AttemptsPerSack'],
      dtype='object')

In [28]:
df.sort_values(by=['AttemptsPerINT'], ascending=False)[:25]

,Player,Team,TeamName,TeamColor,TennColor,Conference,Completions,Attempts,CompletionPct,Yards,...,YPC,Long,TDs,INTs,SacksTaken,QBRating,AttemptsPerINT,INTModYards,INTModYardsPerAtt,AttemptsPerSack
159,Drew Eckels,WKU,NaN,NaN,#74ABD6,NaN,50,99,50.5,709,...,14.2,75,3,0,8,120.7,inf,709,7.16,13.38
143,Shai Werts,GASO,NaN,NaN,#74ABD6,NaN,69,116,59.5,987,...,14.3,61,10,0,19,159.4,inf,987,8.51,7.11
138,Mike Glass III,EMU,NaN,NaN,#74ABD6,NaN,72,117,61.5,1024,...,14.2,76,9,1,11,158.7,117.000000,974,8.32,11.64
154,Zeb Noland,ISU,NaN,NaN,#74ABD6,NaN,70,110,63.6,722,...,10.3,57,4,1,6,129.0,110.000000,672,6.11,19.33
87,Peyton Bender,KU,NaN,NaN,#74ABD6,NaN,183,321,57.0,1894,...,10.3,65,13,3,23,118.1,107.000000,1744,5.43,14.96
21,Trevor Lawrence,CLEM,NaN,NaN,#74ABD6,ACC,259,397,65.2,3280,...,12.7,74,30,4,11,157.6,99.200000,3080,7.76,37.09
9,Mason Fine,UNT,NaN,NaN,#74ABD6,NaN,303,469,64.6,3793,...,12.5,68,27,5,24,149.4,93.800000,3543,7.55,20.54
150,Christian Chapman,SDSU,NaN,NaN,#74ABD6,NaN,51,89,57.3,782,...,15.3,76,4,1,10,143.7,89.000000,732,8.22,9.90
89,Tyler Wiegers,EMU,NaN,NaN,#74ABD6,NaN,171,264,64.8,1887,...,11.0,75,11,3,28,136.3,88.000000,1737,6.58,10.43
94,Holton Ahlers,ECU,NaN,NaN,#74ABD6,NaN,127,263,48.3,1785,...,14.1,80,12,3,14,118.1,87.700000,1635,6.22,19.79
12,Marcus McMaryion,FRES,NaN,NaN,#74ABD6,NaN,293,427,68.6,3629,...,12.4,86,25,5,12,157.0,85.400000,3379,7.91,36.58
20,Sam Ehlinger,TEX,NaN,NaN,#74ABD6,Big12,275,425,64.7,3292,...,12.0,48,25,5,26,146.8,85.000000,3042,7.16,17.35
85,Riley Neal,BALL,NaN,NaN,#74ABD6,NaN,194,335,57.9,1917,...,9.9,52,11,4,14,114.4,83.800000,1717,5.13,24.93
86,Jarrett Guarantano,TENN,Tennessee,#FF8200,#f77f00,SEC,153,246,62.2,1907,...,12.5,55,12,3,22,141.0,82.000000,1757,7.14,12.18
122,Chris Reynolds,CHAR,NaN,NaN,#74ABD6,NaN,101,155,65.2,1181,...,11.7,71,6,2,17,139.4,77.500000,1081,6.97,10.12
126,Conor Blount,ORST,NaN,NaN,#74ABD6,NaN,95,153,62.1,1117,...,11.8,49,7,2,21,135.9,76.500000,1017,6.65,8.29
35,Joe Burrow,LSU,LSU,#461D7C,#74ABD6,SEC,219,379,57.8,2894,...,13.2,71,16,5,35,133.2,75.800000,2644,6.98,11.83
59,Gus Ragland,M-OH,NaN,NaN,#74ABD6,NaN,226,371,60.9,2547,...,11.3,59,17,5,20,131.0,74.200000,2297,6.19,19.55
41,Jarrett Stidham,AUB,Auburn,#0C2340,#74ABD6,SEC,224,369,60.7,2794,...,12.5,76,18,5,23,137.7,73.800000,2544,6.89,17.04
1,Gardner Minshew,WSU,NaN,NaN,#74ABD6,Pac12,468,662,70.7,4779,...,10.2,89,38,9,13,147.6,73.600000,4329,6.54,51.92
142,Cordale Grundy,UTSA,NaN,NaN,#74ABD6,NaN,111,220,50.5,989,...,8.9,52,5,3,16,93.0,73.300000,839,3.81,14.75
145,Davis Shanley,WKU,NaN,NaN,#74ABD6,NaN,96,141,68.1,942,...,9.8,42,3,2,10,128.4,70.500000,842,5.97,15.10
134,Michael Collins,TCU,NaN,NaN,#74ABD6,NaN,79,140,56.4,1059,...,13.4,67,6,2,6,131.3,70.000000,959,6.85,24.33
132,Jonathan Banks,TULN,NaN,NaN,#74ABD6,NaN,72,139,51.8,1074,...,14.9,74,5,2,23,125.7,69.500000,974,7.01,7.04
13,Jordan Love,USU,NaN,NaN,#74ABD6,NaN,267,417,64.0,3567,...,13.4,88,32,6,9,158.3,69.500000,3267,7.83,47.33

# SEC Data

In [29]:
sec_df = df[df['Conference'] == 'SEC'].reset_index(drop=True)

In [30]:
sec_df

,Player,Team,TeamName,TeamColor,TennColor,Conference,Completions,Attempts,CompletionPct,Yards,...,YPC,Long,TDs,INTs,SacksTaken,QBRating,AttemptsPerINT,INTModYards,INTModYardsPerAtt,AttemptsPerSack
0,Tua Tagovailoa,ALA,Alabama,#9e1b32,#74ABD6,SEC,245,355,69.0,3966,...,16.2,81,43,6,13,199.5,59.2,3666,10.33,28.31
1,Jordan Ta'amu,MISS,Ole Miss,#14213D,#74ABD6,SEC,266,418,63.6,3918,...,14.7,84,19,8,29,153.5,52.2,3518,8.42,15.41
2,Drew Lock,MIZ,Missouri,#F1B82D,#74ABD6,SEC,275,437,62.9,3498,...,12.7,86,28,8,13,147.7,54.6,3098,7.09,34.62
3,Jake Bentley,SC,South Carolina,#000000,#74ABD6,SEC,240,388,61.9,3171,...,13.2,89,27,14,20,146.3,27.7,2471,6.37,20.40
4,Kyle Shurmur,VAN,Vanderbilt,#866d4b,#74ABD6,SEC,254,406,62.6,3130,...,12.3,75,24,6,21,143.9,67.7,2830,6.97,20.33
5,Kellen Mond,TA&M,Texas A&M,#500000,#74ABD6,SEC,238,415,57.3,3107,...,13.1,69,24,9,34,135.0,46.1,2657,6.40,13.21
6,Joe Burrow,LSU,LSU,#461D7C,#74ABD6,SEC,219,379,57.8,2894,...,13.2,71,16,5,35,133.2,75.8,2644,6.98,11.83
7,Jarrett Stidham,AUB,Auburn,#0C2340,#74ABD6,SEC,224,369,60.7,2794,...,12.5,76,18,5,23,137.7,73.8,2544,6.89,17.04
8,Jake Fromm,UGA,Georgia,#BA0C2F,#74ABD6,SEC,206,306,67.3,2749,...,13.3,75,30,6,16,171.2,51.0,2449,8.00,20.12
9,Feleipe Franks,FLA,Florida,#0021A5,#74ABD6,SEC,188,322,58.4,2457,...,13.1,65,24,6,15,143.3,53.7,2157,6.70,22.47
10,Jarrett Guarantano,TENN,Tennessee,#FF8200,#f77f00,SEC,153,246,62.2,1907,...,12.5,55,12,3,22,141.0,82.0,1757,7.14,12.18
11,Terry Wilson,UK,Kentucky,#0033a0,#74ABD6,SEC,180,268,67.2,1889,...,10.5,54,11,8,28,134.0,33.5,1489,5.56,10.57
12,Nick Fitzgerald,MSST,Miss State,#660000,#74ABD6,SEC,145,281,51.6,1767,...,12.2,84,16,9,25,116.8,31.2,1317,4.69,12.24
13,Ty Storey,ARK,Arkansas,#9D2235,#74ABD6,SEC,143,250,57.2,1584,...,11.1,57,11,10,19,116.9,25.0,1084,4.34,14.16

In [31]:
sec_df.to_csv(r'sec_qbs_2018.csv')